#!/bin/bash

[[ "$EUID" -eq "0" ]] || { sudo -p "Please enter your password to continue: " "$0" "$@"; exit $?; }

set -e
set -x

rm -f ubuntu.iso

source build.conf

if command -v axel 2> /dev/null; then
		axel -qo ubuntu.iso "$DOWNLOAD_ISO"
	else
		wget -q -O ubuntu.iso "$DOWNLOAD_ISO"
fi

sudo chmod +x ./build/build.sh ./build/switch.sh
sudo make build.iso
