name: Make_Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build OS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso coreutils squashfs-tools git axel sed cd-boot-images-amd64
          
      - name: Build
        run: |
         chmod +x ./fetch_build ./scripts/build.sh ./scripts/switch.sh
         . ./build.conf
         ./fetch_build
         ls -lh .

      - name: Delete pre-existing continuous GitHub Release
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/tags/continuous" | jq -r '.id')
          if [ "$RELEASE_ID" != "null" ]; then
            echo "Deleting existing release..."
            curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"
          fi

      - name: Upload Artifacts to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            rolling*iso*
          tag_name: continuous
          release_name: Continuous
          draft: false
