name: Make_Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build OS
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xorriso coreutils squashfs-tools git axel sed cd-boot-images-amd64
          
      - name: Build
        run: |
         chmod +x ./fetch_build ./build/build.sh ./build/switch.sh ./build/minimal.sh
         . ./fetch_build.conf
         ./fetch_build
         ls -lh .
         make iso
         ls -lh .
