name: Make_Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build OS
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build
        run: |
         sudo apt-get -y install xorriso coreutils squashfs-tools git axel sed
         chmod +x ./fetch_build ./build/build.sh ./build/switch.sh ./build/minimal.sh
         . ./fetch_build.conf
         ./fetch_build
         ./build/build.sh
         ./build/switch.sh
         make iso
